### ISSUE TITLE
alternative format for .yaml database;

### ISSUE THREAD

**Issue by pbosler** [E3SM-Project/PhysicalConstantsDictionary#4]
Summary
====

The current format of `pcd.yaml` may not be as much as we'd like for e3sm.   It might be worth merging its format and entries with a complementary project from a few years ago.

Background
-------

Consistency with physical constants has come up several times over recent years in e3sm, e.g., https://github.com/E3SM-Project/EKAT/issues/48.   Before @rljacob  pointed me to the PhysicalConstantsDictionary, @jeff-cohere and I had decided on the same approach: hold the constants in a .yaml database that could be parsed into auto-generated source files in either c++ or fortran, to use consistently throughout e3sm.   As a fundamental guiding principle, we felt that all constants should be accompanied by metadata that gives a reputable reference source for their value.   Since we're a U.S. government project, we should use NIST or other agencies' publications  (e.g., NASA)  as source documents whenever possible.   

The database that we came up with, now here in the `pbosler/database2` branch file `constants.yaml` reflects several decisions that could be worth revisiting.   To make the database, I grepped through E3SM's main components and gathered as many constants as I could find, searched the SNL library, NIST, etc., to find their source values and reference material, and made this file.   Only after I had done that and presented this work to @mt5555, did I talk to @rljacob and learn about PhysicalConstantsDictionary.   PCD's database has some fields that mine doesn't; mine has some fields that they don't.   PCD has constants that I have not found in E3SM, whereas `constants.yaml` is targeted at E3SM specifically.   It's likely we'll want aspects of both if this effort moves forward.

The basic format for each entry in `constants.yaml` is:

```
Constant_Name:  # human readable standard name
  software_name: code_constant # what you'd see in code
  units: "unit string" # e.g., "W/m2/K4"
  source:
     name: "NIST CODATA 2018"
     url: https://physics.nist.gov/cuu/Constants/index.html
     citation: "E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93." 
```

For derived constants, the source doesn't have to be a citation, it could instead be a definition.  For example, the length of a sidereal day is given as a constant (source: NASA) in `constants.yaml`, so the angular velocity of the Earth can be derived from it as `2*pi / sidereal_day`.   In these cases, the numerical value is computed in double precision and appears as a given value like base constants, but the `source` metadata field contains the definition string, e.g., `"2*pi/sidereal_day"` instead of a citation.  

Some possible points for discussion with @bartgol or @xylar (or others) have come up:

- After finding some numerical ill-conditioning even in algebraic formulas in some components of E3SM, for `constants.yaml` we decided that all constants should use double precision, with as many significant digits as possible.   `pcd.yaml` seems to allow other precision values.
- Some constants have units that are hard to express using just SI terms; for example, seawater isotope ratios like "#17o/#16o" might not be the best way to proceed, but "1" or "non-dimensional" is less expressive and unsatisfying, too.
